node ../cli.js -i src/one-html-file-three-tags/search-bar.html
node ../cli.js -i src/only-css/simple-bling.css
node ../cli.js -i src/only-js/inner-logger.js
node ../cli.js -i src/with-slot/name-tag.html
node ../cli.js -i src/add-more-js/what-fu.html
node ../cli.js -i src/dir-with-three
node ../cli.js -i src/dir-with-one
node ../cli.js -i src/blank-script/ah-choo.html
node ../cli.js -i src/only-html/to-do.html
